name: Java CI with Quarkus

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [16]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.4
      with:
        node-version: 16.x

    - name: Setup Java
      uses: actions/setup-java@v2.7.0
      with:
        java-version: ${{ matrix.java }}
        
    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Test with Quarkus
      run: mvn quarkus:dev
